# Generated by Django 5.2.4 on 2025-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('adhikar', 'आपका अधिकार'), ('bharat', 'भारत'), ('janata', 'जनता की आवाज़'), ('local', 'लोकल खबरें'), ('international', 'अंतर्राष्ट्रीय'), ('opinion', 'ओपिनियन'), ('politics', 'राजनीती'), ('education', 'शिक्षा'), ('society', 'समाज'), ('cyber', 'साइबर सुरक्षा')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news_videos/')),
            ],
        ),
    ]
